name: Visa Bot

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The working directory for the visa bot"
        required: true
        type: string

jobs:
  visa:
    name: Run visa bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
            
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run tests
        id: playwright
        working-directory: ${{ inputs.working-directory }}
        run: |
          # Save the raw output
          raw_output=$(node index.js)
          # Convert to alphanumeric only and underscores
          sanitized_output=$(echo "$raw_output" | sed 's/[^a-zA-Z0-9]/_/g')
          # Store both versions
          echo "SANITIZED_OUTPUT=$sanitized_output" >> $GITHUB_ENV
          echo "RAW_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "$raw_output" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: Hay fechas disponibles para reprogramar tu visa!
          to: ${{ vars.RECIPIENT }}
          from: ${{ vars.SENDER }}
          body: |
            Hemos encontrado una fecha disponible para reprogramar tu visa el día:
            ${{ env.output }}